from pathlib import Path

root = Path('source/TAR-JS')
ui = root / 'app/src/main/java/com/tarjs/archive/NativeUi.kt'
ctl = root / 'app/src/main/java/com/tarjs/archive/TarJsController.kt'
db = root / 'app/src/main/java/com/tarjs/archive/ArchiveDatabase.kt'

# Start by applying the previously generated v4 source snapshot logic from the checked-in native overlay.
# The transformations below are intentionally idempotent only within a fresh reconstructed CI source tree.
s = ui.read_text(encoding='utf-8')

def replace_once(old: str, new: str, name: str):
    global s
    if old not in s:
        raise SystemExit(f'{name} source block not found')
    s = s.replace(old, new, 1)

replace_once('private enum class Page { Chats, Chat, Search, Add, Rclone, Browser, Settings, IndexStatus }', 'private enum class Page { Welcome, Chats, Chat, Search, Add, Rclone, Browser, Settings, IndexStatus }', 'page enum')
replace_once('var page by remember { mutableStateOf(if (archives.isEmpty()) Page.Add else Page.Chats) }', 'var page by remember { mutableStateOf(if (archives.isEmpty()) Page.Welcome else Page.Chats) }', 'initial page')
replace_once('var searchHits by remember { mutableStateOf<List<SearchHit>>(emptyList()) }', 'var searchHits by remember { mutableStateOf<List<SearchHit>>(emptyList()) }\n    var focusMessageId by remember { mutableStateOf<Long?>(null) }\n    var rcloneUnlockTarget by remember { mutableStateOf(Page.Rclone) }', 'focus state')
replace_once('            Page.Chat, Page.Search, Page.Settings, Page.IndexStatus -> page = Page.Chats\n', '            Page.Chat, Page.Settings, Page.IndexStatus -> page = Page.Chats\n            Page.Search -> page = Page.Chat\n', 'back search')
replace_once('            Page.Rclone -> page = Page.Add\n            Page.Add -> page = if (archives.isNotEmpty()) Page.Chats else Page.Add\n            Page.Chats -> if (indexState.active) (context as? Activity)?.moveTaskToBack(true) else (context as? Activity)?.finish()\n', '            Page.Rclone -> page = Page.Add\n            Page.Add -> page = Page.Welcome\n            Page.Chats -> page = Page.Welcome\n            Page.Welcome -> if (indexState.active) (context as? Activity)?.moveTaskToBack(true) else (context as? Activity)?.finish()\n', 'back welcome')
replace_once('    val topTitle = when (page) {\n        Page.Chats -> selectedArchive?.name ?: "TAR-JS"\n', '    val topTitle = when (page) {\n        Page.Welcome -> "TAR-JS"\n        Page.Chats -> selectedArchive?.name ?: "TAR-JS"\n', 'title welcome')
replace_once('        Page.Search -> "Search"\n        Page.Add -> "Add archive"\n', '        Page.Search -> selectedChat?.let { "Search ${it.name}" } ?: "Search chat"\n        Page.Add -> "Add your chats"\n', 'search title')
replace_once('    val topSubtitle = when (page) {\n        Page.Chats -> selectedArchive?.let { "${fmtNum(it.messageCount)} messages" }.orEmpty()\n', '    val topSubtitle = when (page) {\n        Page.Welcome -> "Private Telegram archive reader"\n        Page.Chats -> selectedArchive?.let { "${fmtNum(it.messageCount)} messages" }.orEmpty()\n', 'subtitle welcome')
replace_once('if (page != Page.Chats || (archives.isEmpty() && page != Page.Add)) {', 'if (page != Page.Welcome) {', 'nav visibility')
replace_once('                                    Page.Chat, Page.Search, Page.Settings, Page.IndexStatus -> page = Page.Chats\n', '                                    Page.Chat, Page.Settings, Page.IndexStatus -> page = Page.Chats\n                                    Page.Search -> page = Page.Chat\n', 'nav search')
replace_once('                                    Page.Rclone -> page = Page.Add\n                                    Page.Add -> if (archives.isNotEmpty()) page = Page.Chats\n', '                                    Page.Rclone -> page = Page.Add\n                                    Page.Add, Page.Chats -> page = Page.Welcome\n', 'nav welcome')
s = s.replace('ChatAvatar(controller, selectedChat!!, 36.dp, onClick = { avatarLauncher.launch(arrayOf("image/*")) })', 'ChatAvatar(controller, selectedChat!!, 36.dp, onClick = null)', 1)
s = s.replace('                        if (page == Page.Chats) IconButton(onClick = { page = Page.Search }) { Icon(Icons.Default.Search, "Search") }\n', '', 1)
replace_once('                            if (page == Page.Chat && selectedChat != null) {\n                                DropdownMenuItem(text = { Text("Swap sides") }, leadingIcon = { Icon(Icons.Default.SwapHoriz, null) }, onClick = {\n', '                            if (page == Page.Chat && selectedChat != null) {\n                                DropdownMenuItem(text = { Text("Search this chat") }, leadingIcon = { Icon(Icons.Default.Search, null) }, onClick = {\n                                    searchQuery = ""\n                                    searchHits = emptyList()\n                                    menuOpen = false\n                                    page = Page.Search\n                                })\n                                DropdownMenuItem(text = { Text("Swap sides") }, leadingIcon = { Icon(Icons.Default.SwapHoriz, null) }, onClick = {\n', 'chat menu search')
s = s.replace('Text("Adjust chat photo")', 'Text("Set profile photo")', 1)
replace_once('                    when (page) {\n                        Page.Chats -> ChatListScreen', '                    when (page) {\n                        Page.Welcome -> WelcomeScreen(\n                            hasArchives = archives.isNotEmpty(),\n                            rcloneLocked = rcloneSetup?.passwordRequired == true,\n                            indexState = indexState,\n                            onAdd = { page = Page.Add },\n                            onOpenChats = {\n                                if (rcloneSetup?.passwordRequired == true) { rcloneUnlockTarget = Page.Chats; rclonePasswordDialog = true }\n                                else page = Page.Chats\n                            },\n                            onIndexStatus = { page = Page.IndexStatus },\n                        )\n                        Page.Chats -> ChatListScreen', 'welcome route')
replace_once('                        Page.Chats -> ChatListScreen(chats, indexState, onOpen = { c ->\n                            selectedChat = c\n                            messages = controller.messages(c.id)\n', '                        Page.Chats -> ChatListScreen(chats, indexState, onOpen = { c ->\n                            selectedChat = c\n                            focusMessageId = null\n                            messages = controller.messages(c.id)\n', 'chat focus reset')
replace_once('                                chat = chat,\n                                messages = messages,\n                                onMessages = { messages = it },\n', '                                chat = chat,\n                                messages = messages,\n                                focusMessageId = focusMessageId,\n                                onMessages = { messages = it },\n', 'chat focus parameter')
replace_once('                        Page.Search -> SearchScreen(searchQuery, searchHits, onQuery = { q ->\n                            searchQuery = q\n                            searchHits = selectedArchive?.let { if (q.trim().length >= 2) controller.search(it.id, q) else emptyList() }.orEmpty()\n                        }, onHit = { hit ->\n                            val c = chats.firstOrNull { it.id == hit.chatId }\n                            if (c != null) {\n                                selectedChat = c\n                                messages = controller.messageWindow(c.id, hit.messageDbId)\n                                page = Page.Chat\n                            }\n                        })\n', '                        Page.Search -> SearchScreen(searchQuery, searchHits, onQuery = { q ->\n                            searchQuery = q\n                        }, onHit = { hit ->\n                            val c = selectedChat\n                            if (c != null && c.id == hit.chatId) {\n                                focusMessageId = hit.messageDbId\n                                messages = controller.messageWindow(c.id, hit.messageDbId)\n                                page = Page.Chat\n                            }\n                        })\n', 'scoped async search route')
replace_once('    val rcloneLauncher = rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()) { uri ->\n        if (uri != null) controller.importRcloneConfig(uri) { setup ->\n            rcloneSetup = setup\n            if (setup.passwordRequired) rclonePasswordDialog = true\n            else if (setup.error != null && setup.remotes.isEmpty()) showMessage(setup.error)\n            else page = Page.Rclone\n        }\n    }\n', '    val rcloneLauncher = rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()) { uri ->\n        if (uri != null) controller.importRcloneConfig(uri) { setup ->\n            rcloneSetup = setup\n            if (setup.passwordRequired) { rcloneUnlockTarget = Page.Rclone; rclonePasswordDialog = true }\n            else if (setup.error != null && setup.remotes.isEmpty()) showMessage(setup.error)\n            else page = Page.Rclone\n        }\n    }\n', 'rclone launcher target')
replace_once('    LaunchedEffect(Unit) {\n        controller.startupRclone { setup ->\n            if (setup != null) {\n                rcloneSetup = setup\n                if (setup.passwordRequired) rclonePasswordDialog = true\n            }\n        }\n        if (Build.VERSION.SDK_INT >= 33) notificationPermissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS)\n    }\n', '    LaunchedEffect(Unit) {\n        controller.startupRclone { setup ->\n            if (setup != null) {\n                rcloneSetup = setup\n                if (setup.passwordRequired && archives.isNotEmpty()) {\n                    rcloneUnlockTarget = Page.Chats\n                    rclonePasswordDialog = true\n                } else if (!setup.passwordRequired && archives.isNotEmpty()) {\n                    page = Page.Chats\n                }\n            }\n        }\n        if (Build.VERSION.SDK_INT >= 33) notificationPermissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS)\n    }\n\n    LaunchedEffect(page, selectedChat?.id, searchQuery) {\n        if (page != Page.Search) return@LaunchedEffect\n        val chatId = selectedChat?.id ?: return@LaunchedEffect\n        val q = searchQuery.trim()\n        if (q.length < 2) { searchHits = emptyList(); return@LaunchedEffect }\n        delay(250)\n        searchHits = withContext(Dispatchers.IO) { controller.searchChat(chatId, q) }\n    }\n', 'startup and debounced search')
s = s.replace('onDismiss = { rclonePasswordDialog = false },', 'onDismiss = { rclonePasswordDialog = false; page = if (archives.isEmpty()) Page.Welcome else Page.Chats },', 1)
replace_once('                    controller.unlockRclone(password, remember) { result ->\n                        rcloneSetup = result\n                        if (result.passwordRequired) showMessage(result.error ?: "Incorrect password")\n                        else { rclonePasswordDialog = false; page = Page.Rclone }\n                    }\n', '                    controller.unlockRclone(password, true) { result ->\n                        rcloneSetup = result\n                        if (result.passwordRequired) showMessage(result.error ?: "Incorrect password")\n                        else { rclonePasswordDialog = false; page = rcloneUnlockTarget }\n                    }\n', 'rclone unlock destination')

start = s.index('private fun ChatScreen(')
end = s.index('\n@Composable\nprivate fun MessageRow', start)
s = s[:start] + '''private fun ChatScreen(controller: TarJsController, chat: ChatItem, messages: List<MessageItem>, focusMessageId: Long?, onMessages: (List<MessageItem>) -> Unit, onPickAvatar: () -> Unit) {\n    val swapped = controller.isSwapped(chat.id)\n    val listState = rememberLazyListState(initialFirstVisibleItemIndex = maxOf(0, messages.size - 1))\n    val replies = remember(messages) { messages.mapNotNull { m -> m.telegramId?.let { it to m } }.toMap() }\n    val hasOlder = remember(messages) { messages.firstOrNull()?.let { controller.hasOlder(chat.id, it.dbId) } ?: false }\n    val hasNewer = remember(messages) { messages.lastOrNull()?.let { controller.hasNewer(chat.id, it.dbId) } ?: false }\n    LaunchedEffect(messages, focusMessageId) { val target = focusMessageId ?: return@LaunchedEffect; val index = messages.indexOfFirst { it.dbId == target }; if (index >= 0) listState.scrollToItem(index + if (hasOlder) 1 else 0) }\n    LazyColumn(state = listState, modifier = Modifier.fillMaxSize().background(MaterialTheme.colorScheme.surfaceContainerLowest), contentPadding = PaddingValues(horizontal = 10.dp, vertical = 12.dp), verticalArrangement = Arrangement.spacedBy(3.dp)) {\n        if (hasOlder) item { TextButton(onClick = { val before = messages.firstOrNull()?.dbId ?: return@TextButton; val old = controller.messages(chat.id, before); if (old.isNotEmpty()) onMessages((old + messages).distinctBy { it.dbId }) }, modifier = Modifier.fillMaxWidth()) { Text("Load older messages") } }\n        items(messages, key = { it.dbId }) { message -> MessageRow(controller, message, shouldRenderOnRight(message.mine, swapped), replies[message.replyTo]) }\n        if (hasNewer) item { TextButton(onClick = { val after = messages.lastOrNull()?.dbId ?: return@TextButton; val newer = controller.newerMessages(chat.id, after); if (newer.isNotEmpty()) onMessages((messages + newer).distinctBy { it.dbId }) }, modifier = Modifier.fillMaxWidth()) { Text("Load newer messages") } }\n    }\n}\n''' + s[end:]
s = s.replace('placeholder = { Text("Search all messages") }', 'placeholder = { Text("Search this chat") }', 1)
s = s.replace('headlineContent = { Text(hit.chatName, maxLines = 1) },', 'headlineContent = { Text(hit.sender.ifBlank { hit.chatName }, maxLines = 1) },', 1)
insert = s.index('@Composable\nprivate fun AddArchiveScreen')
s = s[:insert] + '''@Composable\nprivate fun WelcomeScreen(hasArchives: Boolean, rcloneLocked: Boolean, indexState: IndexState, onAdd: () -> Unit, onOpenChats: () -> Unit, onIndexStatus: () -> Unit) {\n    Column(Modifier.fillMaxSize().padding(horizontal = 24.dp, vertical = 28.dp), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.Center) {\n        Surface(shape = RoundedCornerShape(28.dp), color = MaterialTheme.colorScheme.primaryContainer) { Icon(Icons.Default.Forum, null, Modifier.padding(22.dp).size(54.dp), tint = MaterialTheme.colorScheme.onPrimaryContainer) }\n        Spacer(Modifier.height(22.dp)); Text("Your Telegram archive, readable again", style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Bold); Spacer(Modifier.height(10.dp)); Text("TAR-JS privately indexes Telegram exports on your device, keeps the original result.json read-only, and lets you browse chats, search messages and load archived media.", style = MaterialTheme.typography.bodyLarge, color = MaterialTheme.colorScheme.onSurfaceVariant); Spacer(Modifier.height(28.dp))\n        Button(onClick = onAdd, modifier = Modifier.fillMaxWidth()) { Icon(Icons.Default.Add, null); Spacer(Modifier.width(8.dp)); Text("Add your chats") }\n        if (hasArchives) { Spacer(Modifier.height(10.dp)); OutlinedButton(onClick = onOpenChats, modifier = Modifier.fillMaxWidth()) { Icon(if (rcloneLocked) Icons.Default.Lock else Icons.Default.Chat, null); Spacer(Modifier.width(8.dp)); Text(if (rcloneLocked) "Unlock storage" else "Open indexed chats") } }\n        if (indexState.active) { Spacer(Modifier.height(10.dp)); TextButton(onClick = onIndexStatus) { Text("View indexing progress") } }\n    }\n}\n\n''' + s[insert:]
replace_once('private fun AddArchiveScreen(onLocal: (String) -> Unit, onRclone: () -> Unit) {\n    LazyColumn(Modifier.fillMaxSize(), contentPadding = PaddingValues(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {\n        item { Text("Add Telegram archive", style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Bold) }\n        item { Text("TAR-JS reads your export and builds a local searchable index. Original files stay read-only.", color = MaterialTheme.colorScheme.onSurfaceVariant) }\n        item { SourceCard(Icons.Default.Folder, "Local folder", "Phone, SD card or USB") { onLocal("local") } }\n        item { SourceCard(Icons.Default.Cloud, "Cloud document provider", "Google Drive, OneDrive or another Android provider") { onLocal("cloud") } }\n        item { SourceCard(Icons.Default.Lock, "rclone config", "B2, crypt and other rclone remotes") { onRclone() } }\n    }\n}\n', 'private fun AddArchiveScreen(onLocal: (String) -> Unit, onRclone: () -> Unit) {\n    LazyColumn(Modifier.fillMaxSize(), contentPadding = PaddingValues(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {\n        item { Text("Choose where your export is stored", style = MaterialTheme.typography.headlineSmall, fontWeight = FontWeight.Bold) }\n        item { Text("Select the folder that contains result.json. TAR-JS only reads the source and builds its own local index.", color = MaterialTheme.colorScheme.onSurfaceVariant) }\n        item { SourceCard(Icons.Default.Folder, "Local folder", "Phone, SD card or USB") { onLocal("local") } }\n        item { SourceCard(Icons.Default.Cloud, "Google Drive", "Choose a Drive folder through Android's document picker") { onLocal("google_drive") } }\n        item { SourceCard(Icons.Default.Cloud, "OneDrive", "Choose a OneDrive folder through Android's document picker") { onLocal("onedrive") } }\n        item { SourceCard(Icons.Default.Lock, "rclone config", "B2, crypt and other rclone remotes") { onRclone() } }\n    }\n}\n', 'source picker')
replace_once('private fun RclonePasswordDialog(remembered: Boolean, onDismiss: () -> Unit, onUnlock: (String, Boolean) -> Unit) {\n    var password by remember { mutableStateOf("") }\n    var rememberMe by remember { mutableStateOf(remembered) }\n', 'private fun RclonePasswordDialog(remembered: Boolean, onDismiss: () -> Unit, onUnlock: (String, Boolean) -> Unit) {\n    var password by remember { mutableStateOf("") }\n    val rememberMe = true\n', 'rclone remember default')
s = s.replace('                Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.fillMaxWidth().clickable { rememberMe = !rememberMe }.padding(top = 10.dp)) { Checkbox(rememberMe, { rememberMe = it }); Column { Text("Remember me", fontWeight = FontWeight.SemiBold); Text("Store securely on this device", style = MaterialTheme.typography.bodySmall) } }\n', '                Text("This configuration password will be saved securely on this device so future launches only require your TAR-JS passcode.", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant, modifier = Modifier.padding(top = 10.dp))\n', 1)
s = s.replace('dismissButton = { TextButton(onClick = onDismiss) { Text("Not now") } },', 'dismissButton = { TextButton(onClick = onDismiss) { Text("Back") } },', 1)
replace_once('@Composable\nfun TarJsRoot(controller: TarJsController) {', '@Composable\nprivate fun TarJsUnlockedRoot(controller: TarJsController) {', 'root rename')
idx = s.index('@Composable\nprivate fun TarJsUnlockedRoot')
s = s[:idx] + '@Composable\nfun TarJsRoot(controller: TarJsController) {\n    TarJsAppPasscodeGate { TarJsUnlockedRoot(controller) }\n}\n\n' + s[idx:]
ui.write_text(s, encoding='utf-8')

c = ctl.read_text(encoding='utf-8')
needle = '    fun search(archiveId: Long, query: String): List<SearchHit> = runCatching { JsonModels.search(db.searchJson(archiveId, query, 120)) }.getOrDefault(emptyList())\n'
if needle not in c: raise SystemExit('controller search anchor missing')
# Native v2 already contains messageWindow(chatId,messageDbId), so do not add a second overload.
c = c.replace(needle, needle + '    fun searchChat(chatId: Long, query: String): List<SearchHit> = runCatching { JsonModels.search(db.searchChatJson(chatId, query, 120)) }.getOrDefault(emptyList())\n    fun newerMessages(chatId: Long, afterDbId: Long): List<MessageItem> = runCatching { JsonModels.messages(db.newerMessagesJson(chatId, 160, afterDbId)) }.getOrDefault(emptyList())\n    fun hasOlder(chatId: Long, dbId: Long): Boolean = db.hasOlder(chatId, dbId)\n    fun hasNewer(chatId: Long, dbId: Long): Boolean = db.hasNewer(chatId, dbId)\n', 1)
ctl.write_text(c, encoding='utf-8')

d = db.read_text(encoding='utf-8')
# Native v2 already has messageWindowJson(chatId,messageDbId); add scoped search + forward paging only.
anchor = '    fun archiveJson(): String {'
pos = d.find(anchor)
if pos < 0: raise SystemExit('database insert anchor missing')
d = d[:pos] + '''    fun searchChatJson(chatId: Long, query: String, limit: Int): String {\n        val q = query.trim(); if (q.isEmpty()) return "[]"; val a = JSONArray()\n        readableDatabase.rawQuery("SELECT m.id, m.chat_id, c.name, m.sender, m.date_unix, m.text FROM messages m JOIN chats c ON c.id=m.chat_id WHERE m.chat_id=? AND m.text LIKE ? ORDER BY m.date_unix DESC, m.id DESC LIMIT ?", arrayOf(chatId.toString(), "%$q%", limit.coerceIn(1, 500).toString())).use { cur -> while (cur.moveToNext()) a.put(JSONObject().put("messageDbId", cur.getLong(0)).put("chatId", cur.getLong(1)).put("chatName", cur.getString(2) ?: "Chat").put("sender", cur.getString(3) ?: "").put("dateUnix", cur.getLong(4)).put("text", cur.getString(5) ?: "")) }; return a.toString()\n    }\n    fun newerMessagesJson(chatId: Long, limit: Int, afterDbId: Long): String { val a = JSONArray(); readableDatabase.rawQuery("SELECT id, message_id, sender, date_unix, text, media_path, mime_type, reply_to, forwarded_from, edited FROM messages WHERE chat_id=? AND id>? ORDER BY id ASC LIMIT ?", arrayOf(chatId.toString(), afterDbId.toString(), limit.coerceIn(1, 500).toString())).use { cur -> while (cur.moveToNext()) a.put(messageJsonFromCursor(cur, chatId)) }; return a.toString() }\n    fun hasOlder(chatId: Long, dbId: Long): Boolean = readableDatabase.rawQuery("SELECT 1 FROM messages WHERE chat_id=? AND id<? LIMIT 1", arrayOf(chatId.toString(), dbId.toString())).use { it.moveToFirst() }\n    fun hasNewer(chatId: Long, dbId: Long): Boolean = readableDatabase.rawQuery("SELECT 1 FROM messages WHERE chat_id=? AND id>? LIMIT 1", arrayOf(chatId.toString(), dbId.toString())).use { it.moveToFirst() }\n    private fun messageJsonFromCursor(cur: Cursor, chatId: Long): JSONObject {\n        val sender = cur.getString(2) ?: ""\n        val isMine = readableDatabase.rawQuery("SELECT owner_user_id FROM archives a JOIN chats c ON c.archive_id=a.id WHERE c.id=?", arrayOf(chatId.toString())).use { owner -> owner.moveToFirst() && (owner.getString(0)?.let { ownerId -> sender.contains(ownerId.removePrefix("user"), ignoreCase = true) } == true) }\n        return JSONObject().put("dbId", cur.getLong(0)).put("telegramId", if (cur.isNull(1)) JSONObject.NULL else cur.getLong(1)).put("sender", sender).put("mine", isMine).put("dateUnix", cur.getLong(3)).put("text", cur.getString(4) ?: "").put("mediaPath", cur.getString(5)).put("mimeType", cur.getString(6)).put("replyTo", if (cur.isNull(7)) JSONObject.NULL else cur.getLong(7)).put("forwardedFrom", cur.getString(8)).put("edited", cur.getString(9))\n    }\n\n''' + d[pos:]
db.write_text(d, encoding='utf-8')

(root / 'app/src/main/java/com/tarjs/archive/AppPasscode.kt').write_text('''package com.tarjs.archive\nimport android.content.Context\nimport android.util.Base64\nimport java.security.MessageDigest\nimport java.security.SecureRandom\nimport javax.crypto.SecretKeyFactory\nimport javax.crypto.spec.PBEKeySpec\nclass AppPasscode(context: Context) {\n private val prefs=context.getSharedPreferences("tarjs_app_lock",Context.MODE_PRIVATE)\n fun isSet()=prefs.contains("hash")&&prefs.contains("salt")\n fun set(passcode:String){ require(passcode.length>=4); val salt=ByteArray(16).also{SecureRandom().nextBytes(it)}; prefs.edit().putString("salt",Base64.encodeToString(salt,Base64.NO_WRAP)).putString("hash",hash(passcode,salt)).apply() }\n fun verify(passcode:String):Boolean{ val salt=prefs.getString("salt",null)?.let{Base64.decode(it,Base64.NO_WRAP)}?:return false; val expected=prefs.getString("hash",null)?:return false; return MessageDigest.isEqual(expected.toByteArray(),hash(passcode,salt).toByteArray()) }\n private fun hash(passcode:String,salt:ByteArray):String{ val spec=PBEKeySpec(passcode.toCharArray(),salt,120_000,256); val bytes=SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).encoded; spec.clearPassword(); return Base64.encodeToString(bytes,Base64.NO_WRAP) }\n}\n''', encoding='utf-8')

s = ui.read_text(encoding='utf-8'); idx=s.index('@Composable\nfun TarJsRoot(controller: TarJsController) {')
gate='''@Composable\nprivate fun TarJsAppPasscodeGate(content: @Composable () -> Unit) {\n val context=LocalContext.current; val store=remember{AppPasscode(context)}; var unlocked by remember{mutableStateOf(false)}; var creating by remember{mutableStateOf(!store.isSet())}; var passcode by remember{mutableStateOf("")}; var confirm by remember{mutableStateOf("")}; var error by remember{mutableStateOf("")}\n if(unlocked){content();return}; BackHandler{(context as? Activity)?.finish()}\n Box(Modifier.fillMaxSize().padding(WindowInsets.safeDrawing.asPaddingValues()),contentAlignment=Alignment.Center){ Card(Modifier.fillMaxWidth().padding(24.dp),shape=RoundedCornerShape(28.dp)){ Column(Modifier.padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally){ Icon(Icons.Default.Lock,null,Modifier.size(48.dp),tint=MaterialTheme.colorScheme.primary); Spacer(Modifier.height(16.dp)); Text(if(creating)"Protect your chats" else "Unlock TAR-JS",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold); Spacer(Modifier.height(18.dp)); OutlinedTextField(passcode,{passcode=it;error=""},label={Text(if(creating)"New passcode" else "Passcode")},singleLine=true,visualTransformation=PasswordVisualTransformation()); if(creating){Spacer(Modifier.height(10.dp));OutlinedTextField(confirm,{confirm=it;error=""},label={Text("Confirm passcode")},singleLine=true,visualTransformation=PasswordVisualTransformation())}; if(error.isNotBlank()){Text(error,color=MaterialTheme.colorScheme.error)}; Spacer(Modifier.height(18.dp)); Button(onClick={if(creating){if(passcode.length<4)error="Use at least 4 characters" else if(passcode!=confirm)error="Passcodes do not match" else runCatching{store.set(passcode);unlocked=true}.onFailure{error=it.message?:"Could not set passcode"}}else{if(store.verify(passcode))unlocked=true else error="Incorrect passcode"}},modifier=Modifier.fillMaxWidth()){Text(if(creating)"Set passcode" else "Unlock")} } } }\n}\n\n'''
s=s[:idx]+gate+s[idx:]; ui.write_text(s,encoding='utf-8')

test=root/'app/src/test/java/com/tarjs/archive/SearchPagingIntegrationTest.kt'; test.parent.mkdir(parents=True,exist_ok=True)
test.write_text(r'''package com.tarjs.archive\nimport androidx.test.core.app.ApplicationProvider\nimport org.json.JSONArray\nimport org.junit.*\nimport org.junit.runner.RunWith\nimport org.robolectric.RobolectricTestRunner\nimport org.robolectric.annotation.Config\n@RunWith(RobolectricTestRunner::class) @Config(sdk=[30]) class SearchPagingIntegrationTest {\n private val ctx get()=ApplicationProvider.getApplicationContext<android.content.Context>(); private lateinit var db:ArchiveDatabase\n @Before fun setup(){ctx.deleteDatabase("tarjs.db");db=ArchiveDatabase(ctx)}; @After fun teardown(){db.close();ctx.deleteDatabase("tarjs.db")}\n @Test fun searchScopedAndNewerPagingWorks(){ val a=db.createArchive("A","test",null); val c1=db.upsertChat(a,100,"Alice","personal_chat"); val c2=db.upsertChat(a,200,"Bob","personal_chat"); for(i in 1..240)db.insertMessage(c1,i.toLong(),"Alice",i.toLong(),if(i==10)"needle old" else "Alice $i",null,null,null,null,null,false); db.insertMessage(c2,1,"Bob",1,"needle other",null,null,null,null,null,false); val hits=JSONArray(db.searchChatJson(c1,"needle",20)); Assert.assertEquals(1,hits.length()); Assert.assertEquals(c1,hits.getJSONObject(0).getLong("chatId")); val target=hits.getJSONObject(0).getLong("messageDbId"); val window=JSONArray(db.messageWindowJson(c1,target)); val last=window.getJSONObject(window.length()-1).getLong("dbId"); Assert.assertTrue(db.hasNewer(c1,last)); Assert.assertTrue(JSONArray(db.newerMessagesJson(c1,50,last)).length()>0) }\n}\n''',encoding='utf-8')

final_ui=ui.read_text(encoding='utf-8')
assert 'delay(250)' in final_ui and 'withContext(Dispatchers.IO) { controller.searchChat(chatId, q) }' in final_ui
assert 'controller.unlockRclone(password, true)' in final_ui and 'page = rcloneUnlockTarget' in final_ui
print('SECURITY_NAVIGATION_SEARCH_V4_APPLIED')
